version: "3.9"

services:
  app1:
    build: ./app1
    container_name: spring-app1
    networks:
      - backend
    ports:
      - "8080:8080"

  app2:
    build: ./app2
    container_name: spring-app2
    networks:
      - backend
    ports:
      - "8081:8080"

networks:
  backend:
